---

- name: Add MongoDB apt key (Ubuntu)
  apt_key:  id=7F0CEB10
            keyserver=hkp://keyserver.ubuntu.com
  when: ansible_distribution == "Ubuntu"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB apt key (Debian)
  apt_key:  id=EA312927
            keyserver=hkp://keyserver.ubuntu.com
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB repository (Ubuntu)
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
                  state=present
                  update_cache=yes
  when: ansible_distribution == "Ubuntu"
  tags:
    - install
    - mongodb
    - deps

- name: Add MongoDB repository (Debian)
  apt_repository: repo='deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main'
                  state=present
                  update_cache=yes
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == "8"
  tags:
    - install
    - mongodb
    - deps

- name: Disable kernel transparent huge-page defrag
  copy:
    src: 99-thp-defrag.conf
    dest: /etc/sysfs.d/99-thp-defrag.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - mongodb
    - kernel

- name: Install MongoDB
  when: ansible_distribution == "Ubuntu" or ( ansible_distribution == "Debian" and ansible_distribution_major_version == 8)
  apt:  pkg={{ item }}
        state=latest
  with_items:
    - mongodb-org
    - libsnappy1
  tags:
    - install
    - mongodb
    - deps

- name: Install MongoDB
  when: ansible_distribution == "Debian" and ansible_distribution_major_version > 8
  apt:  pkg={{ item }}
        state=latest
  with_items:
    - mongodb
  tags:
    - install
    - mongodb
    - deps

- name: set mongodb_service fact for Debian
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  set_fact:
    mongodb_service: "mongodb"

- name: set mongodb_service fact for Debian
  when: ansible_distribution == "Debian" and ansible_distribution_major_version == 8
  set_fact:
    mongodb_service: "mongod"

- name: Make sure MongoDB is running
  service:  name={{ mongodb_service }}
            state=started
  tags:
    - install
    - mongodb
    - deps
