---
- name: Install OS dependencies
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  apt:  
        pkg: [
          'build-essential', 
          'git', 'lsb-release', 
          'python-apt', 'python3-pip', 
          'python-pycurl', 
          'python3-virtualenv', 
          'python2.7-dev', 'sysfsutils', 
          'python3', 'python3-yaml', 
          'python3-setproctitle',
          'python3-zmq', 
          'libyaml-dev', 
          'libpython2.7-dev', 
          'python3-selinux', 
          'python3-semanage'
        ]
        state: latest
        update_cache: yes
  tags:
    - install
    - deps

- name: Install OS dependencies
  when: ansible_distribution == "CentOS"
  yum:
        pkg: [
          'PyYAML', 
          'git', 
          'libselinux-python', 
          'libsemanage-python', 
          'python-virtualenv', 
          'gcc', 
          'libyaml-devel'
        ]
  tags:
    - install
    - deps

- include: install-mongodb.yml
- include: install-redis.yml
