---
- name: Install OS dependencies
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
  apt:  pkg={{ item }}
        state=latest
        update_cache=yes
  with_items:
    - build-essential
    - git
    - lsb-release
    - python-apt
    - python-pip
    - python-pycurl
    - python-virtualenv
    - python2.7-dev
    - sysfsutils
    - python3
    - python3-yaml
    - python3-setproctitle
    - python3-zmq
    - libyaml-dev
    - libpython2.7-dev
  tags:
    - install
    - deps

- name: Install OS dependencies
  when: ansible_distribution == "CentOS"
  yum:
        pkg={{ item }}
  with_items:
    - PyYAML
    - git
    - libselinux-python
    - libsemanage-python
    - python-virtualenv
    - gcc
  tags:
    - install
    - deps

- include: install-mongodb.yml
- include: install-redis.yml
